# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a24e8cefba88e9345d4f880da2c97d2c76c06d9f1266ea9aec6737fc2e1d975a9dfb23b82dbc24d4028d2dfc9a7f221273ee63abef216088c6e170c7a515696

test:
  secret_key_base: 83b154acf99f5bacf4ae1f2054d71a638681b5e9e6e7a3957a501c2cf191fcb9450db44408421cb3efe471f835032e20982322675c0325a3d7ff6f1089b9e0dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
